// ===================================================================
// サンプルレシピデータ v2
// 100件、全て2人前想定の分量付き
// 材料は { name: '材料名', amount: '分量' } 形式
// ===================================================================

const SAMPLE_DATA_VERSION = 2;

const SAMPLE_RECIPES = [
  // ============== 和食 25件 ==============
  { id: 'r001', name: '肉じゃが', category: '和食', servings: 2,
    ingredients: [
      { name: '牛切り落とし肉', amount: '200g' },
      { name: 'じゃがいも', amount: '300g（中2個）' },
      { name: '人参', amount: '100g（1/2本）' },
      { name: '玉ねぎ', amount: '150g（1個）' },
      { name: 'しらたき', amount: '100g' },
      { name: 'だし汁', amount: '300ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ2' }
    ] },
  { id: 'r002', name: '親子丼', category: '和食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: '玉ねぎ', amount: '120g（小1個）' },
      { name: '卵', amount: '4個' },
      { name: '三つ葉', amount: '少々' },
      { name: 'だし汁', amount: '200ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '小さじ2' },
      { name: 'ご飯', amount: '400g（丼2杯）' }
    ] },
  { id: 'r003', name: '鮭の塩焼き', category: '和食', servings: 2,
    ingredients: [
      { name: '生鮭切り身', amount: '200g（2切れ）' },
      { name: '塩', amount: '小さじ1/2' },
      { name: '大根おろし', amount: '100g' },
      { name: 'すだち', amount: '1個' },
      { name: '醤油', amount: '少々' }
    ] },
  { id: 'r004', name: '味噌汁（豆腐とわかめ）', category: '和食', servings: 2,
    ingredients: [
      { name: '味噌', amount: '大さじ2' },
      { name: 'だし汁', amount: '400ml' },
      { name: '絹豆腐', amount: '150g（1/2丁）' },
      { name: '乾燥わかめ', amount: '3g' },
      { name: '長ねぎ', amount: '20g' }
    ] },
  { id: 'r005', name: '豚の生姜焼き', category: '和食', servings: 2,
    ingredients: [
      { name: '豚ロース肉（しょうが焼き用）', amount: '250g' },
      { name: '生姜（すりおろし）', amount: '20g' },
      { name: '玉ねぎ', amount: '100g（1/2個）' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '酒', amount: '大さじ1' },
      { name: 'キャベツ（千切り）', amount: '150g' },
      { name: 'サラダ油', amount: '大さじ1' }
    ] },
  { id: 'r006', name: 'カツ丼', category: '和食', servings: 2,
    ingredients: [
      { name: '豚ロース肉（とんかつ用）', amount: '200g（2枚）' },
      { name: 'パン粉', amount: '50g' },
      { name: '小麦粉', amount: '大さじ3' },
      { name: '卵（衣用）', amount: '1個' },
      { name: '卵（とじ用）', amount: '3個' },
      { name: '玉ねぎ', amount: '120g（1/2個）' },
      { name: '三つ葉', amount: '少々' },
      { name: 'だし汁', amount: '200ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '揚げ油', amount: '適量' },
      { name: 'ご飯', amount: '400g' }
    ] },
  { id: 'r007', name: 'すき焼き', category: '和食', servings: 2,
    ingredients: [
      { name: '牛肉（すき焼き用）', amount: '300g' },
      { name: '長ねぎ', amount: '120g（1本）' },
      { name: '春菊', amount: '100g' },
      { name: '焼き豆腐', amount: '200g' },
      { name: 'しらたき', amount: '150g' },
      { name: '生椎茸', amount: '60g（4枚）' },
      { name: '醤油', amount: '大さじ4' },
      { name: '砂糖', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ3' },
      { name: '卵（つけ用）', amount: '2個' }
    ] },
  { id: 'r008', name: '天ぷら盛り合わせ', category: '和食', servings: 2,
    ingredients: [
      { name: 'えび', amount: '6尾' },
      { name: 'なす', amount: '1本' },
      { name: 'かぼちゃ', amount: '100g' },
      { name: 'さつまいも', amount: '100g' },
      { name: '小麦粉', amount: '100g' },
      { name: '卵', amount: '1個' },
      { name: '冷水', amount: '150ml' },
      { name: '天つゆ', amount: '100ml' },
      { name: '大根おろし', amount: '50g' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r009', name: 'お好み焼き（豚玉）', category: '和食', servings: 2,
    ingredients: [
      { name: 'キャベツ', amount: '250g' },
      { name: '豚バラ薄切り肉', amount: '120g' },
      { name: '小麦粉', amount: '100g' },
      { name: '卵', amount: '2個' },
      { name: '山芋（すりおろし）', amount: '50g' },
      { name: 'だし汁', amount: '100ml' },
      { name: 'お好み焼きソース', amount: '大さじ4' },
      { name: 'マヨネーズ', amount: '適量' },
      { name: '青のり', amount: '少々' },
      { name: 'かつお節', amount: '5g' }
    ] },
  { id: 'r010', name: 'かけうどん', category: '和食', servings: 2,
    ingredients: [
      { name: 'うどん（茹で）', amount: '400g（2玉）' },
      { name: 'だし汁', amount: '600ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '長ねぎ', amount: '40g' },
      { name: '油揚げ', amount: '1枚' },
      { name: '卵', amount: '2個' }
    ] },
  { id: 'r011', name: '牛丼', category: '和食', servings: 2,
    ingredients: [
      { name: '牛切り落とし肉', amount: '250g' },
      { name: '玉ねぎ', amount: '150g（1個）' },
      { name: 'だし汁', amount: '200ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: '酒', amount: '大さじ2' },
      { name: '生姜（千切り）', amount: '10g' },
      { name: 'ご飯', amount: '400g' },
      { name: '紅生姜', amount: '適量' }
    ] },
  { id: 'r012', name: '天丼', category: '和食', servings: 2,
    ingredients: [
      { name: 'えび', amount: '4尾' },
      { name: 'なす', amount: '1本' },
      { name: 'ピーマン', amount: '2個' },
      { name: 'かぼちゃ', amount: '60g' },
      { name: '小麦粉', amount: '80g' },
      { name: '卵', amount: '1個' },
      { name: '冷水', amount: '120ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ3' },
      { name: 'だし汁', amount: '100ml' },
      { name: '揚げ油', amount: '適量' },
      { name: 'ご飯', amount: '400g' }
    ] },
  { id: 'r013', name: '鶏の唐揚げ', category: '和食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '300g' },
      { name: 'にんにく（すりおろし）', amount: '10g' },
      { name: '生姜（すりおろし）', amount: '10g' },
      { name: '醤油', amount: '大さじ2' },
      { name: '酒', amount: '大さじ1' },
      { name: '片栗粉', amount: '大さじ4' },
      { name: '小麦粉', amount: '大さじ2' },
      { name: 'レモン', amount: '1/2個' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r014', name: '鶏の照り焼き', category: '和食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '300g' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '酒', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ2' },
      { name: 'サラダ油', amount: '大さじ1' },
      { name: 'キャベツ（千切り）', amount: '100g' }
    ] },
  { id: 'r015', name: '焼き鳥（もも・ねぎま）', category: '和食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '250g' },
      { name: '長ねぎ', amount: '100g' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ3' },
      { name: '酒', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: '七味唐辛子', amount: '少々' },
      { name: '竹串', amount: '8本' }
    ] },
  { id: 'r016', name: '茶碗蒸し', category: '和食', servings: 2,
    ingredients: [
      { name: '卵', amount: '2個' },
      { name: 'だし汁', amount: '300ml' },
      { name: '醤油', amount: '小さじ1' },
      { name: 'みりん', amount: '小さじ1' },
      { name: '塩', amount: '少々' },
      { name: '鶏ささみ', amount: '50g' },
      { name: 'えび', amount: '2尾' },
      { name: '椎茸', amount: '2枚' },
      { name: '三つ葉', amount: '少々' },
      { name: 'かまぼこ', amount: '4切れ' }
    ] },
  { id: 'r017', name: 'ぶり大根', category: '和食', servings: 2,
    ingredients: [
      { name: 'ぶり', amount: '300g（2切れ）' },
      { name: '大根', amount: '400g' },
      { name: '生姜（薄切り）', amount: '20g' },
      { name: 'だし汁', amount: '400ml' },
      { name: '醤油', amount: '大さじ4' },
      { name: 'みりん', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ2' },
      { name: '酒', amount: '大さじ3' }
    ] },
  { id: 'r018', name: 'さばの味噌煮', category: '和食', servings: 2,
    ingredients: [
      { name: 'さば', amount: '300g（2切れ）' },
      { name: '生姜（薄切り）', amount: '15g' },
      { name: '味噌', amount: '大さじ3' },
      { name: '醤油', amount: '大さじ1' },
      { name: '砂糖', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '酒', amount: '大さじ3' },
      { name: '水', amount: '150ml' },
      { name: '長ねぎ', amount: '50g' }
    ] },
  { id: 'r019', name: 'きんぴらごぼう', category: '和食', servings: 2,
    ingredients: [
      { name: 'ごぼう', amount: '150g（1本）' },
      { name: '人参', amount: '60g' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: '白ごま', amount: '小さじ1' },
      { name: '七味唐辛子', amount: '少々' }
    ] },
  { id: 'r020', name: '筑前煮', category: '和食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: 'れんこん', amount: '150g' },
      { name: 'ごぼう', amount: '100g' },
      { name: '人参', amount: '100g' },
      { name: '里芋', amount: '150g' },
      { name: 'こんにゃく', amount: '100g' },
      { name: '干し椎茸', amount: '4枚' },
      { name: 'だし汁', amount: '400ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ1' }
    ] },
  { id: 'r021', name: '豚汁', category: '和食', servings: 2,
    ingredients: [
      { name: '豚バラ薄切り肉', amount: '100g' },
      { name: '大根', amount: '100g' },
      { name: '人参', amount: '50g' },
      { name: 'ごぼう', amount: '50g' },
      { name: 'こんにゃく', amount: '80g' },
      { name: '長ねぎ', amount: '40g' },
      { name: '味噌', amount: '大さじ3' },
      { name: 'だし汁', amount: '500ml' },
      { name: 'ごま油', amount: '小さじ1' }
    ] },
  { id: 'r022', name: 'おでん', category: '和食', servings: 2,
    ingredients: [
      { name: '大根', amount: '300g' },
      { name: 'ゆで卵', amount: '4個' },
      { name: 'こんにゃく', amount: '100g' },
      { name: 'ちくわ', amount: '2本' },
      { name: 'はんぺん', amount: '1枚' },
      { name: 'がんもどき', amount: '2個' },
      { name: '昆布', amount: '10g' },
      { name: 'だし汁', amount: '800ml' },
      { name: '醤油', amount: '大さじ3' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '塩', amount: '小さじ1' },
      { name: '酒', amount: '大さじ2' }
    ] },
  { id: 'r023', name: 'ひじきの煮物', category: '和食', servings: 2,
    ingredients: [
      { name: '乾燥ひじき', amount: '20g' },
      { name: '人参', amount: '50g' },
      { name: '油揚げ', amount: '1枚' },
      { name: '大豆水煮', amount: '50g' },
      { name: 'だし汁', amount: '200ml' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'みりん', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ごま油', amount: '小さじ1' }
    ] },
  { id: 'r024', name: '手巻き寿司', category: '和食', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '寿司酢', amount: '大さじ3' },
      { name: '焼き海苔', amount: '6枚' },
      { name: 'まぐろ刺身', amount: '100g' },
      { name: 'サーモン刺身', amount: '100g' },
      { name: 'いか刺身', amount: '60g' },
      { name: 'きゅうり', amount: '1本' },
      { name: '大葉', amount: '6枚' },
      { name: 'たくあん', amount: '50g' },
      { name: '醤油', amount: '適量' },
      { name: 'わさび', amount: '適量' }
    ] },
  { id: 'r025', name: '冷奴', category: '和食', servings: 2,
    ingredients: [
      { name: '絹豆腐', amount: '300g（1丁）' },
      { name: '長ねぎ', amount: '20g' },
      { name: 'みょうが', amount: '1個' },
      { name: '大葉', amount: '4枚' },
      { name: '生姜（すりおろし）', amount: '10g' },
      { name: 'かつお節', amount: '3g' },
      { name: '醤油', amount: '大さじ2' }
    ] },

  // ============== 洋食 25件 ==============
  { id: 'r026', name: 'ハンバーグ', category: '洋食', servings: 2,
    ingredients: [
      { name: '合いびき肉', amount: '300g' },
      { name: '玉ねぎ', amount: '100g（1/2個）' },
      { name: 'パン粉', amount: '30g' },
      { name: '牛乳', amount: '大さじ3' },
      { name: '卵', amount: '1個' },
      { name: 'ナツメグ', amount: '少々' },
      { name: '塩', amount: '小さじ1/2' },
      { name: 'こしょう', amount: '少々' },
      { name: 'ケチャップ', amount: '大さじ3' },
      { name: 'ウスターソース', amount: '大さじ2' },
      { name: '赤ワイン', amount: '大さじ2' },
      { name: 'バター', amount: '10g' }
    ] },
  { id: 'r027', name: 'オムライス', category: '洋食', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '300g' },
      { name: '卵', amount: '4個' },
      { name: '鶏もも肉', amount: '120g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: 'ピーマン', amount: '1個' },
      { name: 'マッシュルーム', amount: '50g' },
      { name: 'ケチャップ', amount: '大さじ5' },
      { name: 'バター', amount: '20g' },
      { name: '牛乳', amount: '大さじ2' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r028', name: 'ビーフカレー', category: '洋食', servings: 2,
    ingredients: [
      { name: '牛肉（カレー用）', amount: '250g' },
      { name: 'じゃがいも', amount: '200g（2個）' },
      { name: '人参', amount: '100g' },
      { name: '玉ねぎ', amount: '200g（1個）' },
      { name: 'カレールー', amount: '80g（4皿分）' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '水', amount: '600ml' },
      { name: 'サラダ油', amount: '大さじ1' },
      { name: 'ご飯', amount: '400g' }
    ] },
  { id: 'r029', name: 'クリームシチュー', category: '洋食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: 'じゃがいも', amount: '200g' },
      { name: '人参', amount: '80g' },
      { name: '玉ねぎ', amount: '150g' },
      { name: 'ブロッコリー', amount: '80g' },
      { name: '牛乳', amount: '400ml' },
      { name: '小麦粉', amount: '大さじ3' },
      { name: 'バター', amount: '30g' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '300ml' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r030', name: 'マカロニグラタン', category: '洋食', servings: 2,
    ingredients: [
      { name: 'マカロニ', amount: '120g' },
      { name: '鶏もも肉', amount: '150g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: 'マッシュルーム', amount: '60g' },
      { name: '牛乳', amount: '400ml' },
      { name: '小麦粉', amount: '大さじ3' },
      { name: 'バター', amount: '30g' },
      { name: 'ピザ用チーズ', amount: '80g' },
      { name: 'パン粉', amount: '大さじ2' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r031', name: 'ペペロンチーノ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'スパゲッティ', amount: '200g' },
      { name: 'にんにく', amount: '3片' },
      { name: '鷹の爪', amount: '2本' },
      { name: 'オリーブオイル', amount: '大さじ4' },
      { name: '塩', amount: '小さじ1' },
      { name: 'パセリ', amount: '少々' }
    ] },
  { id: 'r032', name: 'ミートソースパスタ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'スパゲッティ', amount: '200g' },
      { name: '合いびき肉', amount: '200g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: '人参', amount: '50g' },
      { name: 'セロリ', amount: '40g' },
      { name: 'トマト缶', amount: '1缶（400g）' },
      { name: 'にんにく', amount: '2片' },
      { name: '赤ワイン', amount: '大さじ3' },
      { name: 'コンソメ', amount: '1個' },
      { name: 'パルメザンチーズ', amount: '20g' },
      { name: 'オリーブオイル', amount: '大さじ2' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r033', name: 'ビーフステーキ', category: '洋食', servings: 2,
    ingredients: [
      { name: '牛ステーキ肉', amount: '400g（2枚）' },
      { name: '塩', amount: '小さじ1/2' },
      { name: 'こしょう', amount: '少々' },
      { name: 'にんにく', amount: '2片' },
      { name: 'バター', amount: '20g' },
      { name: 'クレソン', amount: '少々' },
      { name: 'じゃがいも', amount: '150g' },
      { name: 'サラダ油', amount: '大さじ1' }
    ] },
  { id: 'r034', name: 'ロールキャベツ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'キャベツ', amount: '8枚' },
      { name: '合いびき肉', amount: '200g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'パン粉', amount: '20g' },
      { name: '牛乳', amount: '大さじ2' },
      { name: '卵', amount: '1個' },
      { name: 'コンソメ', amount: '2個' },
      { name: 'トマト缶', amount: '1/2缶' },
      { name: 'ベーコン', amount: '40g' },
      { name: '水', amount: '500ml' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r035', name: 'ミネストローネ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'トマト缶', amount: '1缶（400g）' },
      { name: '玉ねぎ', amount: '100g' },
      { name: '人参', amount: '60g' },
      { name: 'セロリ', amount: '40g' },
      { name: 'じゃがいも', amount: '100g' },
      { name: 'ベーコン', amount: '60g' },
      { name: 'にんにく', amount: '1片' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '400ml' },
      { name: 'オリーブオイル', amount: '大さじ2' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r036', name: 'ナポリタン', category: '洋食', servings: 2,
    ingredients: [
      { name: 'スパゲッティ', amount: '200g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: 'ピーマン', amount: '2個' },
      { name: 'マッシュルーム', amount: '60g' },
      { name: 'ウインナー', amount: '4本' },
      { name: 'ケチャップ', amount: '大さじ5' },
      { name: 'バター', amount: '20g' },
      { name: 'オリーブオイル', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'パルメザンチーズ', amount: '適量' }
    ] },
  { id: 'r037', name: 'カルボナーラ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'スパゲッティ', amount: '200g' },
      { name: 'ベーコン（厚切り）', amount: '80g' },
      { name: '卵黄', amount: '4個分' },
      { name: 'パルメザンチーズ', amount: '40g' },
      { name: '生クリーム', amount: '100ml' },
      { name: 'にんにく', amount: '1片' },
      { name: '黒こしょう', amount: '適量' },
      { name: 'オリーブオイル', amount: '大さじ1' }
    ] },
  { id: 'r038', name: 'ポトフ', category: '洋食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: 'じゃがいも', amount: '200g' },
      { name: '人参', amount: '100g' },
      { name: '玉ねぎ', amount: '150g' },
      { name: 'キャベツ', amount: '200g' },
      { name: 'ウインナー', amount: '4本' },
      { name: 'コンソメ', amount: '2個' },
      { name: 'ローリエ', amount: '1枚' },
      { name: '水', amount: '700ml' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r039', name: 'ピザマルゲリータ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'ピザ生地', amount: '2枚' },
      { name: 'トマトソース', amount: '100g' },
      { name: 'モッツァレラチーズ', amount: '150g' },
      { name: 'バジル', amount: '10枚' },
      { name: 'オリーブオイル', amount: '大さじ2' },
      { name: '塩', amount: '少々' }
    ] },
  { id: 'r040', name: 'シーザーサラダ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'ロメインレタス', amount: '200g' },
      { name: 'ベーコン', amount: '60g' },
      { name: 'クルトン', amount: '30g' },
      { name: 'パルメザンチーズ', amount: '20g' },
      { name: 'マヨネーズ', amount: '大さじ3' },
      { name: '牛乳', amount: '大さじ1' },
      { name: 'にんにく（すりおろし）', amount: '少々' },
      { name: 'レモン汁', amount: '小さじ1' },
      { name: '黒こしょう', amount: '少々' }
    ] },
  { id: 'r041', name: 'コロッケ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'じゃがいも', amount: '400g' },
      { name: '合いびき肉', amount: '100g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: '小麦粉', amount: '大さじ3' },
      { name: '卵', amount: '1個' },
      { name: 'パン粉', amount: '60g' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'ナツメグ', amount: '少々' },
      { name: '揚げ油', amount: '適量' },
      { name: 'ウスターソース', amount: '適量' }
    ] },
  { id: 'r042', name: 'エビフライ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'えび（大）', amount: '8尾' },
      { name: '小麦粉', amount: '大さじ3' },
      { name: '卵', amount: '1個' },
      { name: 'パン粉', amount: '60g' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'キャベツ（千切り）', amount: '100g' },
      { name: 'レモン', amount: '1/2個' },
      { name: 'タルタルソース', amount: '大さじ3' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r043', name: 'ビーフシチュー', category: '洋食', servings: 2,
    ingredients: [
      { name: '牛すね肉', amount: '300g' },
      { name: 'じゃがいも', amount: '200g' },
      { name: '人参', amount: '100g' },
      { name: '玉ねぎ', amount: '200g' },
      { name: 'マッシュルーム', amount: '60g' },
      { name: 'ビーフシチュールー', amount: '80g' },
      { name: '赤ワイン', amount: '100ml' },
      { name: 'トマトピューレ', amount: '大さじ2' },
      { name: '水', amount: '600ml' },
      { name: 'バター', amount: '20g' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r044', name: 'プレーンオムレツ', category: '洋食', servings: 2,
    ingredients: [
      { name: '卵', amount: '4個' },
      { name: '牛乳', amount: '大さじ2' },
      { name: 'バター', amount: '20g' },
      { name: '塩', amount: '少々' },
      { name: 'こしょう', amount: '少々' },
      { name: 'ケチャップ', amount: '適量' }
    ] },
  { id: 'r045', name: 'ポークソテー', category: '洋食', servings: 2,
    ingredients: [
      { name: '豚ロース厚切り肉', amount: '300g（2枚）' },
      { name: '塩こしょう', amount: '少々' },
      { name: '小麦粉', amount: '大さじ1' },
      { name: 'バター', amount: '20g' },
      { name: 'にんにく', amount: '1片' },
      { name: 'ウスターソース', amount: '大さじ2' },
      { name: 'ケチャップ', amount: '大さじ1' },
      { name: '白ワイン', amount: '大さじ2' }
    ] },
  { id: 'r046', name: 'チキンソテー', category: '洋食', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '400g（2枚）' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'にんにく', amount: '2片' },
      { name: 'バター', amount: '15g' },
      { name: 'オリーブオイル', amount: '大さじ1' },
      { name: 'ローズマリー', amount: '少々' },
      { name: 'レモン', amount: '1/2個' }
    ] },
  { id: 'r047', name: 'リゾット', category: '洋食', servings: 2,
    ingredients: [
      { name: '米', amount: '160g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'マッシュルーム', amount: '80g' },
      { name: 'ベーコン', amount: '40g' },
      { name: '白ワイン', amount: '50ml' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '500ml' },
      { name: 'パルメザンチーズ', amount: '30g' },
      { name: 'バター', amount: '20g' },
      { name: 'オリーブオイル', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r048', name: 'ラタトゥイユ', category: '洋食', servings: 2,
    ingredients: [
      { name: 'なす', amount: '2本' },
      { name: 'ズッキーニ', amount: '1本' },
      { name: 'パプリカ（赤）', amount: '1個' },
      { name: 'パプリカ（黄）', amount: '1個' },
      { name: '玉ねぎ', amount: '100g' },
      { name: 'にんにく', amount: '2片' },
      { name: 'トマト缶', amount: '1缶（400g）' },
      { name: 'オリーブオイル', amount: '大さじ3' },
      { name: 'コンソメ', amount: '1個' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'ローリエ', amount: '1枚' }
    ] },
  { id: 'r049', name: 'フレンチトースト', category: '洋食', servings: 2,
    ingredients: [
      { name: '食パン（厚切り）', amount: '4枚' },
      { name: '卵', amount: '2個' },
      { name: '牛乳', amount: '200ml' },
      { name: '砂糖', amount: '大さじ2' },
      { name: 'バター', amount: '20g' },
      { name: 'メープルシロップ', amount: '適量' },
      { name: '粉砂糖', amount: '少々' }
    ] },
  { id: 'r050', name: 'クロックムッシュ', category: '洋食', servings: 2,
    ingredients: [
      { name: '食パン', amount: '4枚' },
      { name: 'ハム', amount: '4枚' },
      { name: 'ピザ用チーズ', amount: '80g' },
      { name: 'バター', amount: '20g' },
      { name: '小麦粉', amount: '大さじ1' },
      { name: '牛乳', amount: '100ml' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'パセリ', amount: '少々' }
    ] },

  // ============== 中華 20件 ==============
  { id: 'r051', name: '麻婆豆腐', category: '中華', servings: 2,
    ingredients: [
      { name: '絹豆腐', amount: '300g（1丁）' },
      { name: '豚ひき肉', amount: '150g' },
      { name: '長ねぎ', amount: '50g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '豆板醤', amount: '大さじ1' },
      { name: '甜麺醤', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '鶏がらスープ', amount: '200ml' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: 'ラー油', amount: '少々' }
    ] },
  { id: 'r052', name: '餃子', category: '中華', servings: 2,
    ingredients: [
      { name: '豚ひき肉', amount: '200g' },
      { name: 'キャベツ', amount: '150g' },
      { name: 'にら', amount: '50g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '餃子の皮', amount: '24枚' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' },
      { name: '酢', amount: '適量' },
      { name: 'ラー油', amount: '適量' }
    ] },
  { id: 'r053', name: '青椒肉絲', category: '中華', servings: 2,
    ingredients: [
      { name: '牛もも肉（細切り）', amount: '200g' },
      { name: 'ピーマン', amount: '4個' },
      { name: 'たけのこ水煮', amount: '100g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ1' }
    ] },
  { id: 'r054', name: 'エビチリ', category: '中華', servings: 2,
    ingredients: [
      { name: 'えび', amount: '200g' },
      { name: '長ねぎ', amount: '50g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: 'ケチャップ', amount: '大さじ3' },
      { name: '豆板醤', amount: '小さじ1' },
      { name: '鶏がらスープ', amount: '100ml' },
      { name: '酒', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ2' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: '卵白', amount: '1個分' },
      { name: 'ごま油', amount: '小さじ1' }
    ] },
  { id: 'r055', name: '回鍋肉', category: '中華', servings: 2,
    ingredients: [
      { name: '豚バラ薄切り肉', amount: '200g' },
      { name: 'キャベツ', amount: '250g' },
      { name: 'ピーマン', amount: '2個' },
      { name: '長ねぎ', amount: '50g' },
      { name: 'にんにく', amount: '1片' },
      { name: '甜麺醤', amount: '大さじ2' },
      { name: '豆板醤', amount: '小さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1' },
      { name: 'ごま油', amount: '大さじ1' }
    ] },
  { id: 'r056', name: '八宝菜', category: '中華', servings: 2,
    ingredients: [
      { name: '豚バラ薄切り肉', amount: '100g' },
      { name: 'えび', amount: '8尾' },
      { name: 'いか', amount: '80g' },
      { name: '白菜', amount: '200g' },
      { name: '人参', amount: '50g' },
      { name: 'たけのこ水煮', amount: '60g' },
      { name: '生椎茸', amount: '4枚' },
      { name: 'うずらの卵', amount: '6個' },
      { name: '鶏がらスープ', amount: '200ml' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r057', name: 'チャーハン', category: '中華', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '卵', amount: '2個' },
      { name: '長ねぎ', amount: '50g' },
      { name: 'チャーシュー', amount: '80g' },
      { name: '醤油', amount: '大さじ1' },
      { name: '塩', amount: '小さじ1/2' },
      { name: 'こしょう', amount: '少々' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: 'サラダ油', amount: '大さじ2' }
    ] },
  { id: 'r058', name: '春巻き', category: '中華', servings: 2,
    ingredients: [
      { name: '春巻きの皮', amount: '10枚' },
      { name: '豚肉細切れ', amount: '120g' },
      { name: 'たけのこ', amount: '80g' },
      { name: '生椎茸', amount: '3枚' },
      { name: '春雨', amount: '30g' },
      { name: 'にら', amount: '30g' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: '小麦粉（のり用）', amount: '大さじ1' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r059', name: '酢豚', category: '中華', servings: 2,
    ingredients: [
      { name: '豚肩ロース肉', amount: '200g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: '人参', amount: '60g' },
      { name: 'ピーマン', amount: '2個' },
      { name: 'パイナップル', amount: '80g' },
      { name: '片栗粉', amount: '大さじ3' },
      { name: '酢', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ3' },
      { name: 'ケチャップ', amount: '大さじ2' },
      { name: '醤油', amount: '大さじ1' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r060', name: '担々麺', category: '中華', servings: 2,
    ingredients: [
      { name: '中華麺', amount: '2玉' },
      { name: '豚ひき肉', amount: '120g' },
      { name: '長ねぎ', amount: '30g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '芝麻醤', amount: '大さじ3' },
      { name: '豆板醤', amount: '小さじ1' },
      { name: '鶏がらスープ', amount: '600ml' },
      { name: '醤油', amount: '大さじ2' },
      { name: 'ラー油', amount: '大さじ1' },
      { name: 'チンゲン菜', amount: '1株' },
      { name: '白ごま', amount: '大さじ1' }
    ] },
  { id: 'r061', name: '麻婆茄子', category: '中華', servings: 2,
    ingredients: [
      { name: 'なす', amount: '3本' },
      { name: '豚ひき肉', amount: '120g' },
      { name: '長ねぎ', amount: '40g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '豆板醤', amount: '小さじ2' },
      { name: '甜麺醤', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '鶏がらスープ', amount: '150ml' },
      { name: '片栗粉', amount: '小さじ2' },
      { name: 'ごま油', amount: '大さじ2' }
    ] },
  { id: 'r062', name: '油淋鶏（ユーリンチー）', category: '中華', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '300g' },
      { name: '長ねぎ', amount: '50g' },
      { name: '生姜', amount: '10g' },
      { name: 'にんにく', amount: '1片' },
      { name: '醤油', amount: '大さじ3' },
      { name: '酢', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ2' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: '片栗粉', amount: '大さじ4' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r063', name: 'バンバンジー', category: '中華', servings: 2,
    ingredients: [
      { name: '鶏むね肉', amount: '200g' },
      { name: 'きゅうり', amount: '1本' },
      { name: 'トマト', amount: '1個' },
      { name: '長ねぎ', amount: '30g' },
      { name: '酒', amount: '大さじ1' },
      { name: '練りごま', amount: '大さじ2' },
      { name: '醤油', amount: '大さじ2' },
      { name: '酢', amount: '大さじ1' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: 'ラー油', amount: '少々' }
    ] },
  { id: 'r064', name: '焼売', category: '中華', servings: 2,
    ingredients: [
      { name: '豚ひき肉', amount: '200g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: '焼売の皮', amount: '20枚' },
      { name: '生姜（すりおろし）', amount: '10g' },
      { name: '醤油', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'グリーンピース', amount: '少々' }
    ] },
  { id: 'r065', name: '中華丼', category: '中華', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '豚肉細切れ', amount: '100g' },
      { name: 'えび', amount: '60g' },
      { name: '白菜', amount: '150g' },
      { name: '人参', amount: '40g' },
      { name: '生椎茸', amount: '2枚' },
      { name: 'うずらの卵', amount: '4個' },
      { name: '鶏がらスープ', amount: '300ml' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: 'ごま油', amount: '小さじ1' }
    ] },
  { id: 'r066', name: '五目焼きそば', category: '中華', servings: 2,
    ingredients: [
      { name: '中華蒸し麺', amount: '2玉' },
      { name: '豚肉細切れ', amount: '100g' },
      { name: 'えび', amount: '60g' },
      { name: 'キャベツ', amount: '150g' },
      { name: 'もやし', amount: '100g' },
      { name: '人参', amount: '40g' },
      { name: 'にら', amount: '30g' },
      { name: '鶏がらスープ', amount: '100ml' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ2' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r067', name: '麻婆春雨', category: '中華', servings: 2,
    ingredients: [
      { name: '春雨', amount: '60g' },
      { name: '豚ひき肉', amount: '120g' },
      { name: '長ねぎ', amount: '40g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: '豆板醤', amount: '小さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '鶏がらスープ', amount: '300ml' },
      { name: 'ごま油', amount: '大さじ1' }
    ] },
  { id: 'r068', name: '鶏肉のカシューナッツ炒め', category: '中華', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: 'カシューナッツ', amount: '60g' },
      { name: 'ピーマン', amount: '2個' },
      { name: '玉ねぎ', amount: '80g' },
      { name: '長ねぎ', amount: '30g' },
      { name: 'にんにく', amount: '1片' },
      { name: '生姜', amount: '10g' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '酒', amount: '大さじ1' },
      { name: '片栗粉', amount: '大さじ1' }
    ] },
  { id: 'r069', name: 'エビマヨ', category: '中華', servings: 2,
    ingredients: [
      { name: 'えび', amount: '200g' },
      { name: '片栗粉', amount: '大さじ3' },
      { name: 'マヨネーズ', amount: '大さじ4' },
      { name: '練乳', amount: '大さじ1' },
      { name: 'ケチャップ', amount: '小さじ1' },
      { name: 'レモン汁', amount: '小さじ1' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'レタス', amount: '50g' },
      { name: '揚げ油', amount: '適量' }
    ] },
  { id: 'r070', name: '蟹玉', category: '中華', servings: 2,
    ingredients: [
      { name: '卵', amount: '4個' },
      { name: 'かに缶', amount: '1缶（120g）' },
      { name: '長ねぎ', amount: '40g' },
      { name: '椎茸', amount: '2枚' },
      { name: 'たけのこ', amount: '40g' },
      { name: '鶏がらスープ', amount: '200ml' },
      { name: '酢', amount: '大さじ1' },
      { name: '砂糖', amount: '大さじ1' },
      { name: '醤油', amount: '大さじ1' },
      { name: '片栗粉', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ2' }
    ] },

  // ============== エスニック・アジア 15件 ==============
  { id: 'r071', name: 'ガパオライス', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '鶏ひき肉', amount: '250g' },
      { name: 'パプリカ（赤）', amount: '1/2個' },
      { name: 'ピーマン', amount: '2個' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'にんにく', amount: '2片' },
      { name: '唐辛子', amount: '2本' },
      { name: 'バジル', amount: '20g' },
      { name: 'ナンプラー', amount: '大さじ2' },
      { name: 'オイスターソース', amount: '大さじ1' },
      { name: '砂糖', amount: '小さじ1' },
      { name: '卵', amount: '2個' },
      { name: 'ご飯', amount: '400g' }
    ] },
  { id: 'r072', name: 'パッタイ', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'センレック（タイ米麺）', amount: '160g' },
      { name: 'えび', amount: '8尾' },
      { name: '厚揚げ', amount: '80g' },
      { name: 'もやし', amount: '100g' },
      { name: 'にら', amount: '50g' },
      { name: '卵', amount: '2個' },
      { name: 'ナンプラー', amount: '大さじ2' },
      { name: 'タマリンドペースト', amount: '大さじ1' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ピーナッツ', amount: '30g' },
      { name: 'ライム', amount: '1/2個' },
      { name: 'サラダ油', amount: '大さじ2' }
    ] },
  { id: 'r073', name: 'グリーンカレー', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '200g' },
      { name: 'なす', amount: '1本' },
      { name: 'たけのこ水煮', amount: '80g' },
      { name: 'パプリカ', amount: '1/2個' },
      { name: 'グリーンカレーペースト', amount: '大さじ2' },
      { name: 'ココナッツミルク', amount: '400ml' },
      { name: 'ナンプラー', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'バジル', amount: '10枚' },
      { name: 'ご飯（ジャスミン米）', amount: '400g' }
    ] },
  { id: 'r074', name: 'トムヤムクン', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'えび', amount: '8尾' },
      { name: 'マッシュルーム', amount: '60g' },
      { name: 'レモングラス', amount: '2本' },
      { name: 'バイマックル', amount: '4枚' },
      { name: 'ナンプラー', amount: '大さじ2' },
      { name: 'ライム汁', amount: '大さじ2' },
      { name: '唐辛子', amount: '2本' },
      { name: 'ココナッツミルク', amount: '100ml' },
      { name: '水', amount: '500ml' },
      { name: 'パクチー', amount: '少々' }
    ] },
  { id: 'r075', name: 'プルコギ', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '牛切り落とし肉', amount: '300g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: '人参', amount: '50g' },
      { name: 'ピーマン', amount: '1個' },
      { name: 'えのき', amount: '100g' },
      { name: '醤油', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ2' },
      { name: 'ごま油', amount: '大さじ1' },
      { name: 'にんにく（すりおろし）', amount: '10g' },
      { name: 'コチュジャン', amount: '大さじ1' },
      { name: '白ごま', amount: '大さじ1' }
    ] },
  { id: 'r076', name: 'ビビンバ', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '牛切り落とし肉', amount: '120g' },
      { name: 'ほうれん草', amount: '100g' },
      { name: 'もやし', amount: '100g' },
      { name: '人参', amount: '60g' },
      { name: 'ぜんまい水煮', amount: '60g' },
      { name: '卵', amount: '2個' },
      { name: 'コチュジャン', amount: '大さじ2' },
      { name: 'ごま油', amount: '大さじ2' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'にんにく', amount: '1片' },
      { name: '白ごま', amount: '適量' }
    ] },
  { id: 'r077', name: 'キムチチゲ', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '豚バラ薄切り肉', amount: '150g' },
      { name: '白菜キムチ', amount: '200g' },
      { name: '木綿豆腐', amount: '200g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: '長ねぎ', amount: '40g' },
      { name: 'にら', amount: '30g' },
      { name: 'えのき', amount: '80g' },
      { name: 'コチュジャン', amount: '大さじ1' },
      { name: '味噌', amount: '大さじ1' },
      { name: 'にんにく', amount: '2片' },
      { name: '鶏がらスープ', amount: '600ml' },
      { name: 'ごま油', amount: '大さじ1' }
    ] },
  { id: 'r078', name: 'チャプチェ', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '韓国春雨（タンミョン）', amount: '80g' },
      { name: '牛切り落とし肉', amount: '100g' },
      { name: 'にら', amount: '50g' },
      { name: '人参', amount: '50g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'ピーマン', amount: '1個' },
      { name: '生椎茸', amount: '3枚' },
      { name: '醤油', amount: '大さじ3' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ごま油', amount: '大さじ2' },
      { name: 'にんにく', amount: '1片' },
      { name: '白ごま', amount: '大さじ1' }
    ] },
  { id: 'r079', name: 'タコス', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'トルティーヤ', amount: '6枚' },
      { name: '牛ひき肉', amount: '200g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'レタス', amount: '60g' },
      { name: 'トマト', amount: '1個' },
      { name: 'アボカド', amount: '1個' },
      { name: 'シュレッドチーズ', amount: '60g' },
      { name: 'サルサソース', amount: '大さじ4' },
      { name: 'タコシーズニング', amount: '1袋' },
      { name: 'サワークリーム', amount: '大さじ2' },
      { name: 'ライム', amount: '1/2個' }
    ] },
  { id: 'r080', name: 'インドチキンカレー', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '300g' },
      { name: '玉ねぎ', amount: '200g' },
      { name: 'トマト缶', amount: '1/2缶' },
      { name: 'ヨーグルト', amount: '100g' },
      { name: 'にんにく', amount: '2片' },
      { name: '生姜', amount: '20g' },
      { name: 'カレー粉', amount: '大さじ2' },
      { name: 'クミン', amount: '小さじ1' },
      { name: 'ガラムマサラ', amount: '小さじ1' },
      { name: 'バター', amount: '20g' },
      { name: '生クリーム', amount: '50ml' },
      { name: 'ご飯（バスマティ米）', amount: '300g' }
    ] },
  { id: 'r081', name: 'ナシゴレン', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '鶏もも肉', amount: '120g' },
      { name: 'えび', amount: '80g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'にんにく', amount: '2片' },
      { name: '赤唐辛子', amount: '1本' },
      { name: 'サンバルソース', amount: '大さじ1' },
      { name: 'ケチャップマニス', amount: '大さじ2' },
      { name: 'ナンプラー', amount: '大さじ1' },
      { name: '卵', amount: '2個' },
      { name: 'きゅうり', amount: '1/2本' },
      { name: 'トマト', amount: '1個' }
    ] },
  { id: 'r082', name: 'フォー', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'フォーの麺', amount: '160g' },
      { name: '鶏むね肉', amount: '150g' },
      { name: 'もやし', amount: '100g' },
      { name: '玉ねぎ', amount: '50g' },
      { name: 'パクチー', amount: '20g' },
      { name: 'ライム', amount: '1個' },
      { name: '鶏がらスープ', amount: '800ml' },
      { name: 'ナンプラー', amount: '大さじ2' },
      { name: '生姜', amount: '20g' },
      { name: '八角', amount: '1個' },
      { name: '赤唐辛子', amount: '1本' }
    ] },
  { id: 'r083', name: 'バインミー', category: 'エスニック', servings: 2,
    ingredients: [
      { name: 'バゲット', amount: '2本' },
      { name: '豚レバーパテ', amount: '80g' },
      { name: 'ハム', amount: '80g' },
      { name: '人参', amount: '80g' },
      { name: '大根', amount: '80g' },
      { name: 'きゅうり', amount: '1/2本' },
      { name: 'パクチー', amount: '20g' },
      { name: '酢', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'マヨネーズ', amount: '大さじ2' },
      { name: 'ナンプラー', amount: '小さじ1' }
    ] },
  { id: 'r084', name: 'タンドリーチキン', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '鶏もも肉', amount: '400g' },
      { name: 'プレーンヨーグルト', amount: '100g' },
      { name: 'にんにく（すりおろし）', amount: '2片' },
      { name: '生姜（すりおろし）', amount: '20g' },
      { name: 'カレー粉', amount: '大さじ2' },
      { name: 'パプリカパウダー', amount: '小さじ1' },
      { name: 'ガラムマサラ', amount: '小さじ1' },
      { name: 'レモン汁', amount: '大さじ1' },
      { name: '塩', amount: '小さじ1' },
      { name: 'サラダ油', amount: '大さじ1' }
    ] },
  { id: 'r085', name: 'パエリア', category: 'エスニック', servings: 2,
    ingredients: [
      { name: '米', amount: '160g' },
      { name: '鶏もも肉', amount: '120g' },
      { name: 'えび', amount: '6尾' },
      { name: 'あさり', amount: '150g' },
      { name: 'イカ', amount: '80g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: 'パプリカ', amount: '1/2個' },
      { name: 'にんにく', amount: '2片' },
      { name: 'トマト缶', amount: '1/4缶' },
      { name: 'サフラン', amount: '少々' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '350ml' },
      { name: 'オリーブオイル', amount: '大さじ3' },
      { name: 'レモン', amount: '1/2個' }
    ] },

  // ============== その他・サラダ・軽食 15件 ==============
  { id: 'r086', name: 'ポテトサラダ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'じゃがいも', amount: '300g' },
      { name: '人参', amount: '40g' },
      { name: 'きゅうり', amount: '1/2本' },
      { name: '玉ねぎ', amount: '40g' },
      { name: 'ハム', amount: '2枚' },
      { name: 'ゆで卵', amount: '1個' },
      { name: 'マヨネーズ', amount: '大さじ4' },
      { name: '酢', amount: '小さじ1' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r087', name: '春雨サラダ', category: 'その他', servings: 2,
    ingredients: [
      { name: '春雨', amount: '40g' },
      { name: 'きゅうり', amount: '1本' },
      { name: 'ハム', amount: '3枚' },
      { name: '卵', amount: '2個' },
      { name: '醤油', amount: '大さじ2' },
      { name: '酢', amount: '大さじ2' },
      { name: '砂糖', amount: '大さじ1' },
      { name: 'ごま油', amount: '小さじ1' },
      { name: '白ごま', amount: '小さじ1' }
    ] },
  { id: 'r088', name: 'コブサラダ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'レタス', amount: '100g' },
      { name: 'トマト', amount: '1個' },
      { name: 'アボカド', amount: '1個' },
      { name: 'ゆで卵', amount: '2個' },
      { name: 'グリルチキン', amount: '120g' },
      { name: 'ベーコン', amount: '40g' },
      { name: 'ブルーチーズ', amount: '30g' },
      { name: 'マヨネーズ', amount: '大さじ3' },
      { name: 'ヨーグルト', amount: '大さじ2' },
      { name: 'レモン汁', amount: '小さじ1' }
    ] },
  { id: 'r089', name: 'カプレーゼ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'モッツァレラチーズ', amount: '150g' },
      { name: 'トマト', amount: '2個' },
      { name: 'バジル', amount: '10枚' },
      { name: 'オリーブオイル', amount: '大さじ2' },
      { name: '塩', amount: '少々' },
      { name: '黒こしょう', amount: '少々' },
      { name: 'バルサミコ酢', amount: '小さじ1' }
    ] },
  { id: 'r090', name: 'おにぎり（鮭・梅）', category: 'その他', servings: 2,
    ingredients: [
      { name: 'ご飯', amount: '400g' },
      { name: '塩鮭', amount: '60g' },
      { name: '梅干し', amount: '2個' },
      { name: '焼き海苔', amount: '2枚' },
      { name: '塩', amount: '少々' },
      { name: '白ごま', amount: '少々' }
    ] },
  { id: 'r091', name: 'たまごサンドイッチ', category: 'その他', servings: 2,
    ingredients: [
      { name: '食パン', amount: '4枚' },
      { name: 'ゆで卵', amount: '4個' },
      { name: 'マヨネーズ', amount: '大さじ4' },
      { name: '塩こしょう', amount: '少々' },
      { name: '砂糖', amount: '小さじ1/2' },
      { name: 'バター', amount: '10g' },
      { name: 'パセリ', amount: '少々' }
    ] },
  { id: 'r092', name: 'BLTサンドイッチ', category: 'その他', servings: 2,
    ingredients: [
      { name: '食パン', amount: '4枚' },
      { name: 'ベーコン', amount: '4枚' },
      { name: 'レタス', amount: '60g' },
      { name: 'トマト', amount: '1個' },
      { name: 'マヨネーズ', amount: '大さじ3' },
      { name: '黒こしょう', amount: '少々' },
      { name: 'バター', amount: '10g' }
    ] },
  { id: 'r093', name: 'クラムチャウダー', category: 'その他', servings: 2,
    ingredients: [
      { name: 'あさり水煮缶', amount: '1缶（120g）' },
      { name: 'じゃがいも', amount: '150g' },
      { name: '玉ねぎ', amount: '80g' },
      { name: '人参', amount: '50g' },
      { name: 'ベーコン', amount: '50g' },
      { name: '牛乳', amount: '400ml' },
      { name: 'バター', amount: '20g' },
      { name: '小麦粉', amount: '大さじ2' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '200ml' },
      { name: '塩こしょう', amount: '少々' }
    ] },
  { id: 'r094', name: 'コーンスープ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'コーン缶（クリーム）', amount: '180g' },
      { name: 'コーン缶（粒）', amount: '60g' },
      { name: '玉ねぎ', amount: '60g' },
      { name: '牛乳', amount: '300ml' },
      { name: 'バター', amount: '10g' },
      { name: 'コンソメ', amount: '1個' },
      { name: '水', amount: '100ml' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'パセリ', amount: '少々' }
    ] },
  { id: 'r095', name: 'スクランブルエッグ', category: 'その他', servings: 2,
    ingredients: [
      { name: '卵', amount: '4個' },
      { name: '牛乳', amount: '大さじ2' },
      { name: 'バター', amount: '15g' },
      { name: '塩', amount: '少々' },
      { name: 'こしょう', amount: '少々' }
    ] },
  { id: 'r096', name: 'パンケーキ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'ホットケーキミックス', amount: '200g' },
      { name: '卵', amount: '1個' },
      { name: '牛乳', amount: '150ml' },
      { name: 'バター', amount: '20g' },
      { name: 'メープルシロップ', amount: '適量' },
      { name: '粉砂糖', amount: '少々' }
    ] },
  { id: 'r097', name: 'ジャーマンポテト', category: 'その他', servings: 2,
    ingredients: [
      { name: 'じゃがいも', amount: '300g' },
      { name: 'ベーコン', amount: '80g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: 'にんにく', amount: '1片' },
      { name: 'バター', amount: '15g' },
      { name: 'オリーブオイル', amount: '大さじ1' },
      { name: '塩こしょう', amount: '少々' },
      { name: 'パセリ', amount: '少々' }
    ] },
  { id: 'r098', name: 'アヒージョ', category: 'その他', servings: 2,
    ingredients: [
      { name: 'えび', amount: '8尾' },
      { name: 'マッシュルーム', amount: '80g' },
      { name: 'ブロッコリー', amount: '80g' },
      { name: 'にんにく', amount: '4片' },
      { name: '鷹の爪', amount: '2本' },
      { name: 'オリーブオイル', amount: '150ml' },
      { name: '塩', amount: '小さじ1/2' },
      { name: 'バゲット', amount: '適量' }
    ] },
  { id: 'r099', name: '焼きそば（ソース）', category: 'その他', servings: 2,
    ingredients: [
      { name: '焼きそば麺', amount: '2玉' },
      { name: '豚バラ薄切り肉', amount: '120g' },
      { name: 'キャベツ', amount: '200g' },
      { name: 'もやし', amount: '100g' },
      { name: '人参', amount: '40g' },
      { name: '長ねぎ', amount: '40g' },
      { name: '焼きそばソース', amount: '大さじ4' },
      { name: 'サラダ油', amount: '大さじ1' },
      { name: '青のり', amount: '少々' },
      { name: '紅生姜', amount: '適量' }
    ] },
  { id: 'r100', name: 'カレーうどん', category: 'その他', servings: 2,
    ingredients: [
      { name: 'うどん（茹で）', amount: '400g（2玉）' },
      { name: '豚バラ薄切り肉', amount: '120g' },
      { name: '玉ねぎ', amount: '100g' },
      { name: '長ねぎ', amount: '40g' },
      { name: 'カレールー', amount: '40g（2皿分）' },
      { name: 'だし汁', amount: '600ml' },
      { name: '醤油', amount: '大さじ1' },
      { name: 'みりん', amount: '大さじ1' },
      { name: '片栗粉', amount: '小さじ2' }
    ] }
];

if (typeof window !== 'undefined') {
  window.SAMPLE_RECIPES = SAMPLE_RECIPES;
  window.SAMPLE_DATA_VERSION = SAMPLE_DATA_VERSION;
}
